name: build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: npm install, build, and test
        run: |
          npm i -g npm@7
          npm install
          # npm run lint
          npm run format:check
          npm run compile
          npm run ci:coverage
        env:
          CI: true
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/junit.xml    # Path to test results
          reporter: jest-junit        # Format of test results
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: coverage/coverage-final.json
          flags: unittests # optional
          name: codecov-umbrella # optional
